# Generate the rugarch-sourced half of the FROZEN test-series corpus for
# the copulax/tests/test_timeseries_*.py family.
#
# This script is NOT run standalone in the normal workflow -- it is
# invoked as a subprocess by its Python sibling:
#
#   python copulax/tests/_r_reference/generate_frozen_series_handrolled.py
#
# which merges this script's output with the statsmodels-sourced mean
# series and the four one-time hand-rolled matrix series, and writes the
# single committed module
# copulax/tests/_r_reference/frozen_series_data.py.
#
# To inspect this script's contribution on its own:
#
#   Rscript copulax/tests/_r_reference/generate_frozen_series.R | head
#
#
# Why this exists
# ---------------
# Before this script every test series in the time-series family was
# simulated AT TEST RUNTIME by a hand-rolled recursion in
# copulax/tests/_timeseries_helpers.py. That put a copulax-authored
# formula on both sides of every statistical assertion: the DGP the test
# fits and the estimator it is checking were written by the same hand.
# rugarch (Galanos) is the established third-party GARCH engine already
# used for the 14 committed reference labels in this directory, and its
# ugarchpath() simulator can represent every GARCH-bearing series the
# suite needs. Sourcing the DATA from rugarch and committing it removes
# the hand-rolled DGP entirely and makes every series reproducible,
# reviewable, and identical on every machine and every CI leg.
#
# Values differ from the previous jax-simulated series -- that is
# expected and approved (user mandate 2026-08-03: "i dont give a shit
# about different/frozen numbers"). Assertions that depended on the old
# values are regenerated by the rewire task and recorded in
# .planning/phases/01-time-series-hardening/01-15-AUDIT.md.
#
#
# Corpus scope: consumed-only
# ---------------------------
# The case tables below are PRUNED TO WHAT THE SUITE ACTUALLY READS.
# Every series emitted here is requested by name somewhere in
# copulax/tests/test_timeseries_*.py. Series that no test consumes are
# not generated, not merged and not committed -- carrying them costs
# review surface and megabytes of committed data for no assertion.
#
# The seed variants that USED to live here were retired when several
# call sites that differed only in seed were collapsed onto a single
# draw (the consuming assertions were shape / finiteness / rendering
# checks that never compared two independent realizations). Every
# retired name, and the draw it collapsed onto, is listed in
# .planning/phases/01-time-series-hardening/01-15-AUDIT.md -- sections
# "Seed-variant collapses (B.8)" and "Corpus prune".
#
# When adding a series: add the case here AND the call site that reads
# it in the same change. A case with no consumer will be pruned again.
#
#
# Conventions (shared with the other generate_*_reference.R scripts here)
# ----------------------------------------------------------------------
# * Truth parameters are pinned with ugarchspec(fixed.pars = ...), so the
#   simulated path is drawn from EXACTLY the stated DGP -- there is no
#   fitting step anywhere in this script.
# * Every path is drawn with ugarchpath(..., m.sim = 1, rseed = <seed>).
#   rseed seeds R's RNG, so the path is bit-reproducible across runs,
#   machines and R sessions (verified in the Python driver, which reruns
#   this script and diffs the output).
# * BURN-IN: every path uses n.start = 500 (the N_START constant below).
#   ugarchpath draws n.start + n.sim observations from the pinned spec
#   and returns only the final n.sim, so the returned series carries no
#   dependence on rugarch's pre-sample seeding of the variance and mean
#   recursions -- it is a draw from the stationary distribution of the
#   process to within 500 steps of mixing. 500 also matches the burn-in
#   the suite's own hand-rolled matrix simulator has always used, so the
#   two halves of the corpus share one convention.
# * VARIANCE-ONLY series (the simulate_garch11 replacements) use
#   mean.model = list(armaOrder = c(0, 0), include.mean = FALSE), exactly
#   as generate_garch_standalone_reference.R does, so fitted(sim) is the
#   residual series eps_t itself.
# * MEAN+VARIANCE series (the simulate_ar1_garch11 replacements) use
#   armaOrder = c(1, 0), include.mean = TRUE. rugarch's ARFIMA mean
#   equation applies the AR polynomial to (y_t - mu), i.e. the CENTRED
#   form phi(L)(y_t - mu) = eps_t, which is exactly copulax's convention
#   -- the same mapping generate_arma_garch_reference.R documents
#   (rugarch `mu` -> copulax centred-form unconditional mean).
#
#
# Output format
# -------------
# A Python module fragment on stdout assigning FROZEN_SERIES_RUGARCH, a
# dict of {name: {"y": [...], "y_bits": [...], "provenance": {...}}}.
#
# "y" holds %.17g decimal literals. "y_bits" holds, for the SAME values,
# the big-endian IEEE-754 hexadecimal representation of each double. The
# Python driver parses "y", re-encodes each parsed float, and asserts the
# result equals "y_bits" for every element -- a self-contained proof that
# the R -> Python decimal transfer is lossless to the bit. (R's own
# as.numeric() parser is NOT correctly rounded and cannot round-trip
# %.17g; CPython's float() is, so the check has to happen on the Python
# side. Empirically all 12 + 8 series round-trip exactly.)
#
# Series names encode DGP + length + seed, e.g. "garch11_n2000_s2".

suppressPackageStartupMessages(library(rugarch))

# Burn-in discarded by ugarchpath before the returned sample begins.
N_START <- 500L

# ---------------------------------------------------------------------
# Emission helpers
# ---------------------------------------------------------------------

#' Format one double as a Python float literal at full precision.
#'
#' %.17g is the shortest fixed-width format guaranteed to identify an
#' IEEE-754 double uniquely; the driver verifies the round-trip bitwise.
py_repr_scalar <- function(x) {
  if (is.na(x) || is.nan(x)) return("float('nan')")
  if (is.infinite(x)) return(if (x > 0) "float('inf')" else "float('-inf')")
  sprintf("%.17g", x)
}

#' Format one double for a human-readable provenance `spec` string.
#'
#' Deliberately NOT %.17g: the spec field documents the DGP for a reader,
#' it is not a value that has to round-trip, and %.17g would render 0.05
#' as 0.050000000000000003.
fmt_par <- function(x) sprintf("%g", x)

#' Format a numeric vector as a Python list literal, 6 values per line.
py_repr_list <- function(x, indent) {
  if (length(x) == 0L) return("[]")
  vals <- vapply(x, py_repr_scalar, character(1))
  per_line <- 6L
  n_lines <- ceiling(length(vals) / per_line)
  pad <- strrep(" ", indent)
  lines <- vapply(seq_len(n_lines), function(i) {
    lo <- (i - 1L) * per_line + 1L
    hi <- min(i * per_line, length(vals))
    paste0(pad, paste(vals[lo:hi], collapse = ", "), ",")
  }, character(1))
  paste0("[\n", paste(lines, collapse = "\n"), "\n", strrep(" ", indent - 4L), "]")
}

#' Big-endian IEEE-754 hex representation of each element of x.
#'
#' writeBin(endian = "big") lays the 8 bytes of each double out in
#' network order; as.character() on a raw vector yields lowercase
#' two-digit hex, so the 8 bytes of element j occupy rows 1..8 of
#' column j of the reshaped matrix.
bits_hex <- function(x) {
  b <- as.character(writeBin(as.numeric(x), raw(), endian = "big"))
  m <- matrix(b, nrow = 8L)
  paste0(m[1, ], m[2, ], m[3, ], m[4, ], m[5, ], m[6, ], m[7, ], m[8, ])
}

#' Format a character vector as a Python list literal, 6 values per line.
py_repr_str_list <- function(x, indent) {
  if (length(x) == 0L) return("[]")
  vals <- sprintf("\"%s\"", x)
  per_line <- 6L
  n_lines <- ceiling(length(vals) / per_line)
  pad <- strrep(" ", indent)
  lines <- vapply(seq_len(n_lines), function(i) {
    lo <- (i - 1L) * per_line + 1L
    hi <- min(i * per_line, length(vals))
    paste0(pad, paste(vals[lo:hi], collapse = ", "), ",")
  }, character(1))
  paste0("[\n", paste(lines, collapse = "\n"), "\n", strrep(" ", indent - 4L), "]")
}

ENGINE <- sprintf(
  "rugarch %s / R %s.%s",
  as.character(packageVersion("rugarch")),
  R.Version()$major, R.Version()$minor
)

# ---------------------------------------------------------------------
# Simulators
# ---------------------------------------------------------------------

#' Draw one standalone GARCH(1, 1) residual path from a pinned spec.
#'
#' Replaces copulax/tests/_timeseries_helpers.py::simulate_garch11.
simulate_garch11_path <- function(n, omega, alpha, beta, seed) {
  spec <- ugarchspec(
    mean.model = list(armaOrder = c(0, 0), include.mean = FALSE),
    variance.model = list(model = "sGARCH", garchOrder = c(1, 1)),
    distribution.model = "norm",
    fixed.pars = list(omega = omega, alpha1 = alpha, beta1 = beta)
  )
  sim <- ugarchpath(spec, n.sim = n, n.start = N_START, m.sim = 1,
                    rseed = seed)
  y <- as.numeric(fitted(sim))
  stopifnot(length(y) == n, all(is.finite(y)))
  list(
    y = y,
    spec = sprintf(
      paste0("sGARCH(1,1) omega=%s alpha1=%s beta1=%s; ",
             "mean armaOrder=(0,0) include.mean=FALSE; ",
             "distribution=norm; ugarchpath n.sim=%d n.start=%d m.sim=1"),
      fmt_par(omega), fmt_par(alpha), fmt_par(beta), n, N_START
    )
  )
}

#' Draw one AR(1)-GARCH(1, 1) level path from a pinned spec.
#'
#' Replaces copulax/tests/_timeseries_helpers.py::simulate_ar1_garch11,
#' and also the two AR-injection loops in test_timeseries_diagnostics.py.
#' rugarch's mean equation is centred, phi(L)(y_t - mu) = eps_t, matching
#' copulax exactly.
simulate_ar1_garch11_path <- function(n, phi, mu, omega, alpha, beta, seed) {
  spec <- ugarchspec(
    mean.model = list(armaOrder = c(1, 0), include.mean = TRUE),
    variance.model = list(model = "sGARCH", garchOrder = c(1, 1)),
    distribution.model = "norm",
    fixed.pars = list(mu = mu, ar1 = phi, omega = omega,
                      alpha1 = alpha, beta1 = beta)
  )
  sim <- ugarchpath(spec, n.sim = n, n.start = N_START, m.sim = 1,
                    rseed = seed)
  y <- as.numeric(fitted(sim))
  stopifnot(length(y) == n, all(is.finite(y)))
  list(
    y = y,
    spec = sprintf(
      paste0("sGARCH(1,1) omega=%s alpha1=%s beta1=%s; ",
             "mean armaOrder=(1,0) include.mean=TRUE mu=%s ar1=%s ",
             "(centred: phi(L)(y_t - mu) = eps_t); ",
             "distribution=norm; ugarchpath n.sim=%d n.start=%d m.sim=1"),
      fmt_par(omega), fmt_par(alpha), fmt_par(beta),
      fmt_par(mu), fmt_par(phi), n, N_START
    )
  )
}

# ---------------------------------------------------------------------
# Case tables
#
# One entry per DISTINCT (DGP, parameters, length, seed) tuple the suite
# actually reads, as inventoried in 01-15-AUDIT.md section "Task B
# inventory" and pruned to consumed-only in section "Corpus prune".
# Seeds are carried over unchanged from the jax PRNGKey integers the
# call sites used, so each frozen series stays traceable to the call
# site it replaces.
# ---------------------------------------------------------------------

# Canonical variance truth shared by all but two GARCH series.
W <- 0.05; A <- 0.10; B <- 0.85

GARCH_CASES <- list(
  # (n, seed) pairs on the canonical omega/alpha/beta.
  list(name = "garch11_n250_s2",   n =  250, seed =   2, omega = W, alpha = A, beta = B),
  list(name = "garch11_n300_s4",   n =  300, seed =   4, omega = W, alpha = A, beta = B),
  list(name = "garch11_n400_s1",   n =  400, seed =   1, omega = W, alpha = A, beta = B),
  list(name = "garch11_n500_s2",   n =  500, seed =   2, omega = W, alpha = A, beta = B),
  list(name = "garch11_n600_s2",   n =  600, seed =   2, omega = W, alpha = A, beta = B),
  list(name = "garch11_n800_s102", n =  800, seed = 102, omega = W, alpha = A, beta = B),
  list(name = "garch11_n1000_s42", n = 1000, seed =  42, omega = W, alpha = A, beta = B),
  list(name = "garch11_n1500_s42", n = 1500, seed =  42, omega = W, alpha = A, beta = B),
  list(name = "garch11_n2000_s2",  n = 2000, seed =   2, omega = W, alpha = A, beta = B),
  list(name = "garch11_n3000_s50", n = 3000, seed =  50, omega = W, alpha = A, beta = B),

  # The two alternate parameter sets, both from the GARCH retracing
  # guard in test_timeseries_variance.py (the test needs three
  # genuinely different fits; the parameters, not just the seed, differ).
  list(name = "garch11_w008a006b090_n400_s9", n = 400, seed = 9,
       omega = 0.08, alpha = 0.06, beta = 0.90),
  list(name = "garch11_w005a010b080_n400_s3", n = 400, seed = 3,
       omega = 0.05, alpha = 0.10, beta = 0.80)
)

AR1_GARCH_CASES <- list(
  list(name = "ar1garch11_p050_m010_n500_s13",  n =  500, phi = 0.5, mu = 0.10, seed =  13),
  list(name = "ar1garch11_p050_m010_n1000_s13", n = 1000, phi = 0.5, mu = 0.10, seed =  13),
  list(name = "ar1garch11_p050_m010_n2000_s13", n = 2000, phi = 0.5, mu = 0.10, seed =  13),
  list(name = "ar1garch11_p050_n800_s103",      n =  800, phi = 0.5, mu = 0.00, seed = 103),
  list(name = "ar1garch11_p050_n1500_s13",      n = 1500, phi = 0.5, mu = 0.00, seed =  13),

  # The two diagnostics AR-injection series: the tests used to roll a
  # phi = 0.3 AR(1) component over a GARCH residual series in a Python
  # for-loop of .at[t].set() updates. That DGP IS AR(1)-GARCH(1,1), so
  # rugarch draws it directly and the loop disappears.
  list(name = "ar1garch11_p030_n1500_s7",       n = 1500, phi = 0.3, mu = 0.00, seed =   7),
  list(name = "ar1garch11_p030_n1500_s42",      n = 1500, phi = 0.3, mu = 0.00, seed =  42),
  list(name = "ar1garch11_p030_n4000_s0",       n = 4000, phi = 0.3, mu = 0.00, seed =   0)
)

# ---------------------------------------------------------------------
# Emit
# ---------------------------------------------------------------------

emit_case <- function(name, y, spec, seed, n) {
  cat(sprintf("    \"%s\": {\n", name))
  cat(sprintf("        \"y\": %s,\n", py_repr_list(y, 12L)))
  cat(sprintf("        \"y_bits\": %s,\n", py_repr_str_list(bits_hex(y), 12L)))
  cat("        \"provenance\": {\n")
  cat("            \"generator\": \"generate_frozen_series.R\",\n")
  cat(sprintf("            \"engine\": \"%s\",\n", ENGINE))
  cat(sprintf("            \"spec\": \"%s\",\n", spec))
  cat(sprintf("            \"seed\": %d,\n", as.integer(seed)))
  cat(sprintf("            \"n\": %d,\n", as.integer(n)))
  cat("        },\n")
  cat("    },\n")
}

cat("# Auto-generated by generate_frozen_series.R -- do not edit.\n")
cat("# Consumed by generate_frozen_series_handrolled.py, which merges this\n")
cat("# fragment into frozen_series_data.py. Not committed on its own.\n\n")
cat("FROZEN_SERIES_RUGARCH = {\n")

for (cfg in GARCH_CASES) {
  res <- simulate_garch11_path(cfg$n, cfg$omega, cfg$alpha, cfg$beta, cfg$seed)
  emit_case(cfg$name, res$y, res$spec, cfg$seed, cfg$n)
}

for (cfg in AR1_GARCH_CASES) {
  res <- simulate_ar1_garch11_path(cfg$n, cfg$phi, cfg$mu, W, A, B, cfg$seed)
  emit_case(cfg$name, res$y, res$spec, cfg$seed, cfg$n)
}

cat("}\n")
