# Generate rugarch reference data for the fGARCH submodel="TGARCH" Layer-1
# tests in copulax/tests/test_timeseries_variance.py.
#
# Run from project root:
#   Rscript copulax/tests/_r_reference/generate_tgarch_fgarch_reference.R \
#       > copulax/tests/_r_reference/tgarch_fgarch_reference_data.py
#
# WHAT THIS FIXTURE IS FOR (read carefully -- the reported sigma path here is
# NOT reproduced by CopulAX's clean Zakoian recursion; see the "C-source
# finding" block below and 01-04-SUMMARY.md).
# --------------------------------------------------------------------------
# HARD-02 (TGARCH) cross-validation against rugarch's fGARCH submodel="TGARCH".
# Each case: specify a TGARCH(1,1) fGARCH spec (armaOrder=c(0,0),
# include.mean=FALSE), simulate n=2000, refit (free params), and capture:
#   * the fitted rugarch coefficients omega/alpha1/beta1/eta11,
#   * the RQ1 mapping to CopulAX convention alpha_pos = alpha*(1 - eta11),
#     alpha_neg = alpha*(1 + eta11) (beta, omega identical),
#   * the FULL reported conditional-sd path sigma(fit) (**and its square**),
#   * loglik, AIC, BIC (per-obs -> absolute via *N), standard errors,
#   * a mechanical coef(fit) check that lambda/delta are fixed at 1.
#
# RQ1 mapping (D-03 pre-approved TGARCH conform-to-literature conversion)
# ----------------------------------------------------------------------
# rugarch fGARCH (Hentschel 1995 omnibus) with submodel="TGARCH" restrictions
# lambda=delta=1, eta2=0, |eta1|<=1. CopulAX TGARCH is the Zakoian (1994)
# sigma-form with sign-split coefficients:
#   sigma_t = omega + alpha_pos*eps^+_{t-1} + alpha_neg*eps^-_{t-1} + beta*sigma_{t-1}
# Expanding alpha_pos*eps^+ + alpha_neg*eps^- with the mapping gives
#   alpha*|eps_{t-1}| - alpha*eta11*eps_{t-1}, i.e. the vignette fGARCH-TGARCH
# formula sigma_t = omega + alpha*(|eps_{t-1}| - eta11*eps_{t-1}) + beta*sigma_{t-1}.
# rugarch reports (alpha1, eta11, beta1, omega); the mapping is the sanctioned
# TGARCH conform-to-literature conversion (recorded for 01-MATH-REVIEW.md).
#
# ==========================================================================
# C-SOURCE FINDING (Option B reverse-engineering result) -- rugarch 1.5-5
# ==========================================================================
# The VIGNETTE fGARCH-TGARCH formula above (plain |eps|) does NOT reproduce
# rugarch's REPORTED sigma(fit) path at rtol<=1e-8: it diverges at ~4.2e-5
# (peak). Reverse-engineering the rugarch 1.5-5 C source
# (src/filters.c :: fgarchfilter, called by src/garchmodels.c ::
# fgarchfilterC, glued in R/rugarch-fgarch.R) reveals the reported path is
# generated by the Hentschel (1995) omnibus recursion in *standardized-z*
# space with a Box-Cox-softened absolute value:
#
#   filters.c line 162 (single-lag, kdelta=lambda=1, eta2=0 for TGARCH):
#     h[i] = omega
#          + alpha1 * ( ( sqrt(0.001^2 + (z_{i-1})^2) - eta11 * z_{i-1} )^kdelta
#                       * h_{i-1}^lambda )
#          + beta1 * h_{i-1}^lambda
#   where h == sigma (kdelta=1) and z_{i-1} = res_{i-1}/h_{i-1}.
#
# In raw-eps space this is
#   sigma_t = omega
#           + alpha1 * ( sqrt(0.001^2 * sigma_{t-1}^2 + eps_{t-1}^2)
#                        - eta11 * eps_{t-1} )
#           + beta1 * sigma_{t-1}.
# The `sqrt(0.001^2 + z^2)` softening of |z| (a fixed 1e-3 smoothing constant
# hard-coded in the C news-impact function) is the EXACT reason the vignette
# |eps| formula is ~4.2e-5 off. Confirmed empirically: this C-exact formula
# reproduces sigma(fit) to ~5.8e-16 (machine precision) on 3 seeds; the
# vignette |eps| formula peaks at 4.2e-5.
#
# Pre-sample (fgarchfilterC lines 254-262): h[i] = hEst for i in 0..m-1, where
# hEst = mvar = mean(|res[1:n]|)^lambda ^ (1/lambda) = mean(|res|) for TGARCH
# (R/rugarch-fgarch.R line 283, rec.init type==1 "all"). eta1 default 0.05 and
# submodel fixing (lambda=1, delta=1, eta2=0, fk=0 => kdelta=1) are set in
# R/rugarch-startpars.R :: .fgarchModel("TGARCH").
#
# CONSEQUENCE FOR THE LAYER-1 GATE: CopulAX's PRODUCTION TGARCH recursion is
# the clean Zakoian |eps| form (no 0.001 softening) and must NOT be changed to
# mimic rugarch (project decision). So CopulAX's Zakoian
# recursion at the mapped params does NOT match rugarch's reported sigma at
# 1e-8 (measured ~4.2e-5 with the pre-sample matched). The co-located
# reference module reproduces the C-exact formula and DEMONSTRATES it matches
# rugarch at 1e-8, and documents the divergence from CopulAX's Zakoian form.
# The Zakoian production recursion is instead validated as a Layer-1 gate
# against the `arch` TARCH/ZARCH (power=1, o=1) oracle -- see 01-04-SUMMARY.md
# (Option A) once the user selects the resolution.
#
# Residual laws (copulax <-> rugarch): normal <-> norm, student_t <-> std.

suppressPackageStartupMessages(library(rugarch))

# ---------------------------------------------------------------------
# Python-repr helpers (identical convention to
# generate_garch_standalone_reference.R).
# ---------------------------------------------------------------------
py_repr_scalar <- function(x) {
  if (is.logical(x)) return(if (x) "True" else "False")
  if (is.character(x)) return(sprintf("\"%s\"", x))
  if (is.na(x) || is.nan(x)) return("float('nan')")
  if (is.infinite(x)) return(if (x > 0) "float('inf')" else "float('-inf')")
  sprintf("%.17g", x)
}

py_repr_array <- function(x) {
  if (length(x) == 0) return("np.array([], dtype=float)")
  body <- paste(sapply(x, py_repr_scalar), collapse=", ")
  sprintf("np.array([%s], dtype=float)", body)
}

py_repr_tuple <- function(x) {
  if (length(x) == 0) return("()")
  body <- paste(sapply(x, py_repr_scalar), collapse=", ")
  if (length(x) == 1) sprintf("(%s,)", body) else sprintf("(%s)", body)
}

cx_residual_name <- function(rugarch_name) {
  switch(rugarch_name,
    "norm" = "normal",
    "std"  = "student_t",
    stop("cx_residual_name: unsupported ", rugarch_name)
  )
}

# ---------------------------------------------------------------------
# Per-case driver
# ---------------------------------------------------------------------
process_case <- function(label, residual_dist, fixed_pars, residual_shape_truth,
                         n_sim = 2000, seed = 77) {
  vlist <- list(model="fGARCH", submodel="TGARCH", garchOrder=c(1, 1))
  spec_truth <- ugarchspec(
    mean.model=list(armaOrder=c(0,0), include.mean=FALSE),
    variance.model=vlist,
    distribution.model=residual_dist,
    fixed.pars=fixed_pars
  )
  sim <- ugarchpath(spec_truth, n.sim=n_sim, m.sim=1, rseed=seed)
  y <- as.numeric(fitted(sim))
  spec <- ugarchspec(
    mean.model=list(armaOrder=c(0,0), include.mean=FALSE),
    variance.model=vlist,
    distribution.model=residual_dist
  )
  fit <- ugarchfit(spec=spec, data=y, solver="hybrid")
  cf <- coef(fit)

  # --- A1 mechanical check: lambda / delta must NOT be free in coef(fit). ---
  # For the named submodel rugarch fixes them (they never appear in coef());
  # if either appears, the fixture is invalid -- fail loudly (no silent failures).
  cf_names <- names(cf)
  if (any(cf_names == "lambda") || any(cf_names == "delta")) {
    stop(sprintf(
      "A1 violation for %s: lambda/delta appear as FREE params in coef(): %s",
      label, paste(cf_names, collapse=", ")))
  }
  # Positive confirmation from the spec's fixed fmodel parameters.
  fm <- spec@model$fmodel$fpars
  if (fm$lambda != 1 || fm$delta != 1 || fm$eta2 != 0 || fm$fk != 0) {
    stop(sprintf(
      "A1 violation for %s: TGARCH submodel expected lambda=delta=1, eta2=fk=0; got lambda=%g delta=%g eta2=%g fk=%g",
      label, fm$lambda, fm$delta, fm$eta2, fm$fk))
  }

  mc <- fit@fit$matcoef
  se <- mc[, 2]; names(se) <- rownames(mc)
  ll <- as.numeric(fit@fit$LLH)
  N <- length(y)
  ic <- infocriteria(fit)
  aic_total <- as.numeric(ic[1, 1]) * N
  bic_total <- as.numeric(ic[2, 1]) * N
  sig <- as.numeric(sigma(fit))
  res <- as.numeric(residuals(fit))
  # rugarch's reported UNCONDITIONAL variance for the fGARCH-TGARCH fit.
  # IMPORTANT (VERIFIED empirically, 01-MATH-REVIEW.md unconditional-
  # variance third-party section): uncvariance is a CLOSED-FORM accessor
  # derived from the fitted coefficients, NOT from the 0.001-softened
  # reported sigma path. It equals (omega/(1 - persistence))^2 with the
  # SAME first-moment persistence copulax's clean Zakoian form uses
  # (alpha_pos*E[z+] + alpha_neg*E[z-] + beta) -- so the 0.001 news-impact
  # softening (which perturbs sigma(fit) at O(1e-5), finding 1) does NOT
  # enter uncvariance. copulax's Zakoian stats()["unconditional_variance"]
  # (== unconditional_sigma^2) therefore matches this TIGHTLY, not at the
  # softening-widened tolerance. Captured as the third-party oracle.
  uncvar <- tryCatch(uncvariance(fit),
                     error = function(e) NA_real_)

  omega  <- unname(cf["omega"])
  alpha1 <- unname(cf["alpha1"])
  beta1  <- unname(cf["beta1"])
  eta11  <- unname(cf["eta11"])

  # RQ1 mapping -> CopulAX (alpha_pos / alpha_neg) convention.
  alpha_pos <- alpha1 * (1 - eta11)
  alpha_neg <- alpha1 * (1 + eta11)

  # Pre-sample warm value rugarch actually uses for TGARCH (lambda=1):
  # mvar = mean(|res[1:N]|).  rec.init="all" (type==1) uses the whole window.
  pre_sample_sigma <- mean(abs(res))

  # SEs: rugarch reports SE(alpha1), SE(eta11); the SE of the derived
  # alpha_pos/alpha_neg is a linear combination we do NOT emit (the CopulAX
  # test compares its on-basis SE separately).  We emit rugarch's native SEs.
  list(
    label                = label,
    residual_dist        = cx_residual_name(residual_dist),
    residual_shape_truth = residual_shape_truth,
    y                    = y,
    # rugarch-native fitted params (for provenance / C-exact reference).
    rugarch_params       = list(omega=omega, alpha1=alpha1, beta1=beta1, eta11=eta11),
    # CopulAX-convention mapped params.
    params               = list(omega=omega, alpha_pos=alpha_pos,
                                alpha_neg=alpha_neg, beta=beta1),
    residual             = switch(residual_dist,
                                  "norm" = list(),
                                  "std"  = list(nu = unname(cf["shape"]))),
    standard_errors      = list(omega=unname(se["omega"]),
                                alpha1=unname(se["alpha1"]),
                                beta1=unname(se["beta1"]),
                                eta11=unname(se["eta11"])),
    residual_se          = switch(residual_dist,
                                  "norm" = list(),
                                  "std"  = list(nu = unname(se["shape"]))),
    loglikelihood        = ll,
    aic                  = aic_total,
    bic                  = bic_total,
    sigma                = sig,
    sigma2               = sig^2,
    pre_sample_sigma     = pre_sample_sigma,
    uncvariance          = uncvar
  )
}

CASES <- list(
  list(label="tgarch11_normal", residual_dist="norm",
       fixed_pars=list(omega=0.03, alpha1=0.10, beta1=0.88, eta11=0.30),
       residual_shape_truth=list(), seed=77),
  list(label="tgarch11_studentt", residual_dist="std",
       fixed_pars=list(omega=0.03, alpha1=0.10, beta1=0.88, eta11=0.30, shape=7.0),
       residual_shape_truth=list(nu=7.0), seed=87)
)

# ---------------------------------------------------------------------
# Emit Python output to stdout.
# ---------------------------------------------------------------------
cat("\"\"\"Auto-generated rugarch reference data for fGARCH submodel=\"TGARCH\".\n\n")
cat("Regenerate with:\n")
cat("    Rscript copulax/tests/_r_reference/generate_tgarch_fgarch_reference.R \\\n")
cat("        > copulax/tests/_r_reference/tgarch_fgarch_reference_data.py\n\n")
cat("rugarch ", as.character(packageVersion("rugarch")),
    " on R ", paste(R.Version()$major, R.Version()$minor, sep="."),
    ".\n\n", sep="")
cat("RQ1 mapping (CopulAX convention): alpha_pos = alpha1*(1 - eta11),\n")
cat("alpha_neg = alpha1*(1 + eta11); beta, omega identical. lambda/delta\n")
cat("confirmed fixed at 1 (A1, mechanical coef() + fmodel check).\n\n")
cat("CRITICAL: rugarch's REPORTED sigma path is generated by the Hentschel\n")
cat("(1995) omnibus fGARCH C recursion with a hard-coded sqrt(0.001^2 + z^2)\n")
cat("softening of |z| (src/filters.c::fgarchfilter). It is NOT reproduced by\n")
cat("CopulAX's clean Zakoian |eps| recursion at 1e-8 (~4.2e-5 off). The\n")
cat("C-exact formula is reproduced/asserted at 1e-8 in the co-located\n")
cat("reference module; see the .R header and 01-04-SUMMARY.md for the full\n")
cat("finding and the Layer-1 resolution.\n\n")
cat("`uncvariance` is rugarch's reported UNCONDITIONAL variance. Unlike the\n")
cat("softened sigma PATH above, uncvariance is a CLOSED-FORM accessor:\n")
cat("(omega/(1 - persistence))^2 with the same first-moment persistence\n")
cat("copulax's clean Zakoian form uses (alpha_pos*E[z+] + alpha_neg*E[z-] +\n")
cat("beta). The 0.001 softening does NOT enter it, so copulax's Zakoian\n")
cat("stats()[\"unconditional_variance\"] matches it TIGHTLY (not at the\n")
cat("softening-widened path tolerance) -- the third-party oracle for that\n")
cat("accessor (TestUnconditionalVarianceThirdParty).\n")
cat("\"\"\"\n\n")
cat("import numpy as np\n\n")
cat("TGARCH_FGARCH_REFERENCE = {\n")

emit_kv_dict <- function(d) {
  for (k in names(d)) {
    cat(sprintf("            \"%s\": %s,\n", k, py_repr_scalar(d[[k]])))
  }
}
emit_residual_dict <- function(d) {
  if (length(d) == 0) { cat("{}"); return(invisible(NULL)) }
  parts <- sapply(names(d), function(k) sprintf("\"%s\": %s", k, py_repr_scalar(d[[k]])))
  cat(sprintf("{%s}", paste(parts, collapse=", ")))
}

for (cfg in CASES) {
  res <- process_case(
    label=cfg$label, residual_dist=cfg$residual_dist,
    fixed_pars=cfg$fixed_pars, residual_shape_truth=cfg$residual_shape_truth,
    seed=cfg$seed
  )
  cat(sprintf("    \"%s\": {\n", res$label))
  cat(sprintf("        \"residual_dist\":        \"%s\",\n", res$residual_dist))
  cat(sprintf("        \"residual_shape_truth\": ")); emit_residual_dict(res$residual_shape_truth); cat(",\n")
  cat(sprintf("        \"y\":                    %s,\n", py_repr_array(res$y)))
  cat("        \"rugarch_params\": {\n"); emit_kv_dict(res$rugarch_params); cat("        },\n")
  cat("        \"params\": {\n"); emit_kv_dict(res$params); cat("        },\n")
  cat(sprintf("        \"residual\":             ")); emit_residual_dict(res$residual); cat(",\n")
  cat("        \"standard_errors\": {\n"); emit_kv_dict(res$standard_errors); cat("        },\n")
  cat(sprintf("        \"residual_se\":          ")); emit_residual_dict(res$residual_se); cat(",\n")
  cat(sprintf("        \"loglikelihood\":        %s,\n", py_repr_scalar(res$loglikelihood)))
  cat(sprintf("        \"aic\":                  %s,\n", py_repr_scalar(res$aic)))
  cat(sprintf("        \"bic\":                  %s,\n", py_repr_scalar(res$bic)))
  cat(sprintf("        \"pre_sample_sigma\":     %s,\n", py_repr_scalar(res$pre_sample_sigma)))
  cat(sprintf("        \"sigma\":                %s,\n", py_repr_array(res$sigma)))
  cat(sprintf("        \"sigma2\":               %s,\n", py_repr_array(res$sigma2)))
  cat(sprintf("        \"uncvariance\":          %s,\n", py_repr_scalar(res$uncvariance)))
  cat("    },\n")
}

cat("}\n")
