"""Validate Archimedean copula CDF/PDF/fit/sample against the R copula package.

The existing copulax tests cover mathematical properties (generator
identities, Frechet bounds, sampling uniformity) but never compare
*numerical values* against an independent implementation. This file
closes that gap by checking copulax against the **R copula package
v1.1.2** (gold standard, hardcoded reference values):

- CDF/PDF values at fixed u-points (all 5 families x 3 thetas)
- itau fit results on R-generated data (all 5 families)
- Empirical Kendall's tau and bivariate CDF from large R samples

All bivariate (d=2). Three theta levels per copula for CDF/PDF
(weak / moderate / strong) at 8 fixed u-points covering the
interior, near boundaries, and corners. One moderate theta per
family for fitting and sampling.
"""

import jax
import jax.numpy as jnp
import numpy as np
import pytest

from copulax.copulas import (
    clayton_copula, frank_copula, gumbel_copula,
    joe_copula, amh_copula,
)


# ---------------------------------------------------------------------------
# Test points and parameter grid
# ---------------------------------------------------------------------------

U_POINTS = np.array([
    [0.30, 0.70],
    [0.50, 0.50],
    [0.10, 0.90],
    [0.90, 0.10],
    [0.05, 0.05],
    [0.95, 0.95],
    [0.01, 0.50],
    [0.50, 0.99],
])


COPULA_BY_NAME = {
    "Clayton": clayton_copula,
    "Frank": frank_copula,
    "Gumbel": gumbel_copula,
    "Joe": joe_copula,
    "AMH": amh_copula,
}


def _make_params(copula, theta):
    """Build a bivariate params dict with the supplied theta."""
    params = copula.example_params(dim=2)
    params["copula"]["theta"] = jnp.array(float(theta))
    return params


def _copulax_cdf(copula, theta, u=U_POINTS):
    return np.asarray(
        copula.copula_cdf(u=jnp.array(u), params=_make_params(copula, theta))
    ).flatten()


def _copulax_pdf(copula, theta, u=U_POINTS):
    return np.asarray(
        copula.copula_pdf(u=jnp.array(u), params=_make_params(copula, theta))
    ).flatten()


# ---------------------------------------------------------------------------
# R copula package reference values (hardcoded)
# ---------------------------------------------------------------------------
#
# Generated by copulax/tests_new/generate_r_reference.R against
# R copula package version 1.1.2 on 2026-04-17.
# To regenerate: Rscript copulax/tests_new/generate_r_reference.R

R_REFERENCE_DATA = {
    ("Clayton", 0.5): {
        "cdf": np.array([2.4483870034809105e-01, 2.9911947447943626e-01, 9.6664706574113857e-02, 9.6664706574113857e-02, 1.5844983787854240e-02, 9.0365835539128225e-01, 9.2203422331812654e-03, 4.9645667134663846e-01]),
        "pdf": np.array([9.3437766348186002e-01, 1.0736695201542492e+00, 5.1911474983664041e-01, 5.1911474983664041e-01, 3.0127621348483635e+00, 1.4286603118853660e+00, 3.6068687145523559e-01, 1.0615639526192844e+00]),
    },
    ("Clayton", 2.0): {
        "cdf": np.array([2.8686490250570262e-01, 3.7796447300922725e-01, 9.9882921979759301e-02, 9.9882921979759301e-02, 3.5377456883861257e-02, 9.0682052381636047e-01, 9.9985003374156479e-03, 4.9873580759885860e-01]),
        "pdf": np.array([6.2928945100121725e-01, 1.4810036493422789e+00, 4.0911925523127050e-02, 4.0911925523127050e-02, 1.0639819990415695e+01, 2.5025705362850075e+00, 2.3982009445749301e-03, 7.6323523098840851e-01]),
    },
    ("Clayton", 8.0): {
        "cdf": np.array([2.9995980534969396e-01, 4.5861408372267709e-01, 9.9999999834617839e-02, 9.9999999834617839e-02, 4.5850202160345500e-02, 9.1616617396770084e-01, 9.9999999999999690e-03, 4.9997956348082156e-01]),
        "pdf": np.array([1.4599599074839011e-02, 4.1436972639909362e+00, 2.3230572472291871e-07, 2.3230572472291871e-07, 4.1265181945923032e+01, 5.1142259987169316e+00, 4.6079999999997124e-13, 3.8457763174031240e-02]),
    },
    ("Frank", 1.0): {
        "cdf": np.array([2.3118814877435495e-01, 2.8092980362016134e-01, 9.3583431312790746e-02, 9.3583431312790746e-02, 3.7699381033722747e-03, 9.0376993810337214e-01, 6.2128335738450818e-03, 4.9621283357384499e-01]),
        "pdf": np.array([9.2408746099428851e-01, 1.0207470412683990e+00, 7.0176408549389324e-01, 7.0176408549389324e-01, 1.4422653275052930e+00, 1.4422653275052923e+00, 9.6184767056055620e-01, 9.6184767056055531e-01]),
    },
    ("Frank", 5.0): {
        "cdf": np.array([2.8419478481814092e-01, 3.7714851074652084e-01, 9.9429847757870296e-02, 9.9429847757870296e-02, 1.0103142862678723e-02, 9.1010314286267868e-01, 9.2236423677994183e-03, 4.9922364236779943e-01]),
        "pdf": np.array([5.8166913472935688e-01, 1.4735637245846294e+00, 9.1675247934184564e-02, 9.1675247934184564e-02, 3.3778185121129884e+00, 3.3778185121129831e+00, 4.3103546174240576e-01, 4.3103546174240537e-01]),
    },
    ("Frank", 15.0): {
        "cdf": np.array([2.9983859647954358e-01, 4.5382705006102769e-01, 9.9999752787282681e-02, 9.9999752787282681e-02, 2.1752023105973253e-02, 9.2175202310597326e-01, 9.9940363659380780e-03, 4.9999403636593809e-01]),
        "pdf": np.array([3.7001693444717806e-02, 3.7541504283131348e+00, 9.2162529977845263e-05, 9.2162529977845263e-05, 6.4276641606125882e+00, 6.4276641606125837e+00, 9.6371640240581705e-03, 9.6371640240581619e-03]),
    },
    ("Gumbel", 1.5): {
        "cdf": np.array([2.6443888022048573e-01, 3.3277038426286515e-01, 9.8511124270163258e-02, 9.8511124270163258e-02, 8.6048561846660387e-03, 9.2180365883980364e-01, 8.3729752167742057e-03, 4.9959687897624189e-01]),
        "pdf": np.array([8.5356800306151115e-01, 1.2195734798973541e+00, 2.8281019514589628e-01, 2.8281019514589628e-01, 2.3962681694946255e+00, 4.5946192305281830e+00, 6.9095612351863112e-01, 2.0885457241494373e-01]),
    },
    ("Gumbel", 3.0): {
        "cdf": np.array([2.9691245262918037e-01, 4.1756681003292112e-01, 9.9992647226380973e-02, 9.9992647226380973e-02, 2.2951174867548517e-02, 9.3741845962772608e-01, 9.9478522062814139e-03, 4.9999964784086542e-01]),
        "pdf": np.array([3.1740548323937273e-01, 2.1808532175286044e+00, 4.3461210003482454e-03, 4.3461210003482454e-03, 5.5737961182968174e+00, 1.3168925035818818e+01, 6.4333455828351815e-02, 8.2510128127336383e-04]),
    },
    ("Gumbel", 8.0): {
        "cdf": np.array([2.9999732155871311e-01, 4.6959607894677202e-01, 9.9999999999446906e-02, 9.9999999999446906e-02, 3.8125603704587716e-02, 9.4559990370653468e-01, 9.9999984836696542e-03, 4.9999999999999989e-01]),
        "pdf": np.array([1.9491679159436715e-03, 5.7300572821682021e+00, 1.8853016373540845e-09, 1.8853016373540845e-09, 1.4248872819264443e+01, 3.9293705898591192e+01, 8.8205158969473612e-06, 1.5105293994488577e-12]),
    },
    ("Joe", 1.5): {
        "cdf": np.array([2.4675061516274843e-01, 3.0283575486720982e-01, 9.6754368128601831e-02, 9.6754368128601831e-02, 3.6593995033432636e-03, 9.2092601840064781e-01, 6.4587179046311505e-03, 4.9939070987130063e-01]),
        "pdf": np.array([9.3184095407753909e-01, 1.1131915768612448e+00, 4.9951582889038881e-01, 4.9951582889038881e-01, 1.4302386055053431e+00, 4.1760850003520922e+00, 1.0622151836085791e+00, 2.4101644529146246e-01]),
    },
    ("Joe", 3.0): {
        "cdf": np.array([2.8813490436222289e-01, 3.8344698141738243e-01, 9.9888491182621664e-02, 9.9888491182621664e-02, 6.8271338952052840e-03, 9.3700525995035955e-01, 8.7389382469034160e-03, 4.9999883333605555e-01]),
        "pdf": np.array([5.6950569211573043e-01, 1.5674147850189220e+00, 3.7415375347275077e-02, 3.7415375347275077e-02, 2.5115199181099768e+00, 1.2602097993022236e+01, 7.6139991822693154e-01, 1.6999808668436106e-03]),
    },
    ("Joe", 8.0): {
        "cdf": np.array([2.9990619991508072e-01, 4.5487936617495062e-01, 9.9999998511560495e-02, 9.9999998511560495e-02, 1.4916697817510483e-02, 9.4547461336687022e-01, 9.9595340380598252e-03, 4.9999999999999845e-01]),
        "pdf": np.array([2.6721164955093260e-02, 3.8350609510900173e+00, 1.7261400772814475e-06, 1.7261400772814475e-06, 4.8187257907723033e+00, 3.8167770645107744e+01, 6.7040062022367078e-02, 1.7929999999999137e-11]),
    },
    ("AMH", -0.5): {
        "cdf": np.array([1.9004524886877827e-01, 2.2222222222222221e-01, 8.6124401913875617e-02, 8.6124401913875617e-02, 1.7226528854435836e-03, 9.0137328339575529e-01, 4.0080160320641279e-03, 4.9376558603491272e-01]),
        "pdf": np.array([1.0728320477723403e+00, 1.0096021947873799e+00, 1.2947282324911287e+00, 1.2947282324911287e+00, 7.1138998661888653e-01, 5.9713295120599374e-01, 9.6127612915156857e-01, 1.0012220460968153e+00]),
    },
    ("AMH", 0.3): {
        "cdf": np.array([2.2411953041622193e-01, 2.7027027027027029e-01, 9.2497430626927016e-02, 9.2497430626927016e-02, 3.4281796366129593e-03, 9.0317738303727768e-01, 5.8719906048150328e-03, 4.9574361542313478e-01]),
        "pdf": np.array([9.5045692757914391e-01, 1.0076402187432139e+00, 7.9800920683337750e-01, 7.9800920683337750e-01, 1.3201383311630335e+00, 1.2437713872818841e+00, 9.7030689079702825e-01, 1.0004452540141018e+00]),
    },
    ("AMH", 0.9): {
        "cdf": np.array([2.5893958076448814e-01, 3.2258064516129009e-01, 9.7932535364526702e-02, 9.7932535364526702e-02, 1.3315579227696399e-02, 9.0453520420947053e-01, 9.0171325518485120e-03, 4.9723756906077332e-01]),
        "pdf": np.array([8.6068598292600884e-01, 1.1332281561545445e+00, 3.2712683116571578e-01, 3.2712683116571578e-01, 3.5168176683333119e+00, 1.7359664281737879e+00, 3.7802303993094427e-01, 1.0040436855951147e+00]),
    },
}


R_CASES = list(R_REFERENCE_DATA.keys())
R_IDS = [f"{name}-theta{theta:g}" for (name, theta) in R_CASES]


# ---------------------------------------------------------------------------
# 1. R copula package reference (CDF + PDF)
# ---------------------------------------------------------------------------

class TestArchimedeanAgainstRCopula:
    """Compare copulax CDF/PDF against hardcoded R copula v1.1.2 values.

    The R `copula` package is the de-facto reference implementation in
    statistics research (used by McNeil, Hofert, et al). All five
    Archimedean families covered.
    """

    @pytest.mark.parametrize("name,theta", R_CASES, ids=R_IDS)
    def test_cdf_matches_r(self, name, theta):
        copula = COPULA_BY_NAME[name]
        expected = R_REFERENCE_DATA[(name, theta)]["cdf"]
        actual = _copulax_cdf(copula, theta)
        np.testing.assert_allclose(
            actual, expected, rtol=1e-10, atol=1e-12,
            err_msg=f"{name} theta={theta} CDF mismatch vs R copula",
        )

    @pytest.mark.parametrize("name,theta", R_CASES, ids=R_IDS)
    def test_pdf_matches_r(self, name, theta):
        copula = COPULA_BY_NAME[name]
        expected = R_REFERENCE_DATA[(name, theta)]["pdf"]
        actual = _copulax_pdf(copula, theta)
        # PDF tolerance looser because copulax uses autodiff for the
        # generic path while R uses hand-coded closed forms; rounding
        # accumulates differently.
        np.testing.assert_allclose(
            actual, expected, rtol=1e-6, atol=1e-10,
            err_msg=f"{name} theta={theta} PDF mismatch vs R copula",
        )


# ---------------------------------------------------------------------------
# 2. Fitting against R copula (itau on R-generated data)
# ---------------------------------------------------------------------------
#
# The reference data (R-generated samples + R itau fits) lives in
# _r_reference/fit_sample_data.py, generated by generate_fit_sample.R.
# Loaded via importlib because the directory has no __init__.py
# (it's data, not a package).

import importlib.util as _importlib_util
import pathlib as _pathlib

_data_path = _pathlib.Path(__file__).parent / "_r_reference" / "fit_sample_data.py"
_spec = _importlib_util.spec_from_file_location("_r_fit_sample", _data_path)
_r_data = _importlib_util.module_from_spec(_spec)
_spec.loader.exec_module(_r_data)
FIT_DATA = _r_data.FIT_DATA
SAMPLE_STATS = _r_data.SAMPLE_STATS


# Per-family tolerances for fit theta_hat agreement with R.
# Both use itau (Kendall's tau inversion); differences come purely
# from the tau->theta inversion method:
#   - Clayton, Gumbel: closed-form inversion -> machine precision
#   - AMH: near-closed-form (Taylor near 0) -> ~1e-8
#   - Joe: bisection in copulax -> ~1e-4
#   - Frank: Debye function approximation differs between R and
#     copulax (same approximation family, different polynomial
#     truncation) -> ~1e-2
# Each tolerance was chosen as 5x the observed gap on the reference
# dataset, so a future regression that meaningfully changes the
# inversion will fail.
FIT_TOLERANCES = {
    "Clayton": 1e-12,
    "Gumbel":  1e-12,
    "AMH":     1e-7,
    "Joe":     1e-3,
    "Frank":   1e-2,
}

FIT_CASES = list(FIT_DATA.keys())


class TestArchimedeanFitAgainstRCopula:
    """Fit copulax on R-generated data and compare theta_hat to R's itau fit.

    Both R::fitCopula(method="itau") and copulax.fit_copula() compute
    Kendall's tau on the data and invert. The empirical Kendall's tau
    is identical (verified separately), so any difference between the
    two theta_hat values is purely from the tau->theta inversion.
    """

    @pytest.mark.parametrize("name", FIT_CASES, ids=FIT_CASES)
    def test_theta_hat_matches_r_itau(self, name):
        copula = COPULA_BY_NAME[name]
        ref = FIT_DATA[name]
        u = jnp.array(ref["u"])
        theta_hat_cx = float(copula.fit_copula(u=u)["copula"]["theta"])
        np.testing.assert_allclose(
            theta_hat_cx, ref["theta_hat_r"],
            rtol=FIT_TOLERANCES[name],
            err_msg=(
                f"{name}: copulax fit theta_hat={theta_hat_cx} "
                f"differs from R itau theta_hat={ref['theta_hat_r']} "
                f"on R-generated data (theta_true={ref['theta_true']})"
            ),
        )


# ---------------------------------------------------------------------------
# 3. Sampling against R copula (empirical stats from large samples)
# ---------------------------------------------------------------------------
#
# Both samplers should produce the same population distribution. With
# n=50000 from each, empirical statistics from independent samples
# differ by ~sqrt(2)*SE.
#
# Empirical Kendall's tau SE: sqrt((1-tau^2)/n) ~ 0.003 for tau=0.5
#   -> two-sample diff ~ 0.005 -> 4-sigma tolerance ~ 0.02
# Empirical CDF point SE: sqrt(p(1-p)/n) <= sqrt(0.25/50000) ~ 0.0022
#   -> two-sample diff ~ 0.003 -> 4-sigma tolerance ~ 0.015 (atol)
#
# Tolerances are conservative enough to avoid flakes but tight enough
# to catch real sampler regressions.

SAMPLE_TAU_TOL = 0.02
SAMPLE_CDF_ATOL = 0.015

SAMPLE_CASES = list(SAMPLE_STATS.keys())


def _empirical_bivariate_cdf(samples, points):
    """P[U1 <= p1, U2 <= p2] for each row of points."""
    return np.array([
        np.mean((samples[:, 0] <= p[0]) & (samples[:, 1] <= p[1]))
        for p in points
    ])


class TestArchimedeanSamplingAgainstRCopula:
    """Compare copulax samples to R rCopula() samples via empirical stats.

    Generates n=50000 samples in copulax with a fixed key, then checks
    that the empirical Kendall's tau and the empirical bivariate CDF at
    U_POINTS agree with the same statistics from R-generated samples
    of the same size. Tolerances allow ~4-sigma deviation between two
    independent Monte Carlo samples.
    """

    @pytest.mark.parametrize("name", SAMPLE_CASES, ids=SAMPLE_CASES)
    def test_sample_empirical_stats_match_r(self, name):
        import scipy.stats
        copula = COPULA_BY_NAME[name]
        ref = SAMPLE_STATS[name]
        n = ref["n"]

        params = _make_params(copula, ref["theta"])
        key = jax.random.PRNGKey(2024)
        samples = np.asarray(copula.copula_rvs(size=n, params=params, key=key))

        # Drop any non-finite rows (sampling can produce NaNs near
        # boundaries for some frailty distributions).
        finite = np.all(np.isfinite(samples), axis=1)
        samples = samples[finite]
        assert len(samples) > 0.99 * n, (
            f"{name}: too many non-finite samples "
            f"({n - len(samples)} of {n})"
        )

        tau_emp_cx = scipy.stats.kendalltau(
            samples[:, 0], samples[:, 1]
        ).statistic
        cdf_emp_cx = _empirical_bivariate_cdf(samples, U_POINTS)

        np.testing.assert_allclose(
            tau_emp_cx, ref["tau_emp_r"],
            atol=SAMPLE_TAU_TOL,
            err_msg=(
                f"{name}: empirical Kendall's tau differs by more than "
                f"{SAMPLE_TAU_TOL} between copulax ({tau_emp_cx:.4f}) "
                f"and R ({ref['tau_emp_r']:.4f})"
            ),
        )
        np.testing.assert_allclose(
            cdf_emp_cx, ref["cdf_emp_r"],
            atol=SAMPLE_CDF_ATOL,
            err_msg=(
                f"{name}: empirical CDF at U_POINTS differs by more "
                f"than {SAMPLE_CDF_ATOL} between copulax and R\n"
                f"  copulax: {cdf_emp_cx}\n"
                f"  R:       {ref['cdf_emp_r']}"
            ),
        )
